spring:
  data:
    mongodb:
      database: ${MONGO_DB_NAME}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      port: 27017
      host: localhost
      authentication-database: admin